# Build Init
image: Visual Studio 2019 Preview
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 --Target="AppVeyor"

# Tests
test: off

# Artifacts
artifacts:
# Static website
  - path: output

# Branches to build
branches:
  # Whitelist
  only:
    - master
