Type: Addin
Name: Cake.Netlify
NuGet: Cake.Netlify
Assemblies:
- "/**/Cake.Netlify.dll"
Repository: https://github.com/cake-contrib/Cake.Netlify/
Author: Jamie Phillips
Description: Cake addin for Netlify
Categories:
- netlify
- deployment
TargetCakeVersion: 0.33.0
AnalyzedPackageVersion: 0.12.0
