Type: Addin
Name: Cake.AppVeyor
NuGet: Cake.AppVeyor
Assemblies:
- /**/Cake.AppVeyor.dll
Repository: https://github.com/cake-contrib/Cake.AppVeyor.git
ProjectUrl: https://github.com/cake-contrib/Cake.AppVeyor/
Author: Jonathan Dick
Description: A set of aliases for Cake to access the AppVeyor REST API's
Categories:
- appveyor
TargetCakeVersion: 6.0.0
TargetFrameworks:
- net8.0
- net9.0
- net10.0
AnalyzedPackageVersion: 10.0.0
AnalyzedPackageIsPrerelease: false
AnalyzedPackagePublishDate: 2025-12-11T10:34:46.8830000Z
