Type: Addin
Name: Cake.CodeGen.OpenAPI
NuGet: Cake.CodeGen.OpenAPI
Assemblies:
- "/**/Cake.CodeGen.OpenAPI.dll"
Repository: https://github.com/lukoerfer/cake-openapi-generator.git
ProjectUrl: https://github.com/lukoerfer/cake-codegen-openapi/
Author: lukoerfer
Description: Cake Addin for code generation via the OpenAPI Generator (f.k.a. Swagger Codegen)
Categories:
- code generation
- openapi
TargetCakeVersion: 0.33.0
TargetFrameworks:
- netstandard2.0
AnalyzedPackageVersion: 1.0.2
AnalyzedPackageIsPrerelease: false
AnalyzedPackagePublishDate: 2020-01-29T13:53:18.5700000Z
