Name: Cake.Microsoft.Extensions.Configuration
NuGet: Cake.Microsoft.Extensions.Configuration
Assemblies:
- "/**/Cake.Microsoft.Extensions.Configuration.dll"
Repository: https://www.nuget.org/packages/Cake.Microsoft.Extensions.Configuration/
Author: Jonathan Kuleff
Description: Cake Addin for strongly typed configuration
Categories:
- configuration
